AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CodeCommitSourceBucket:
    Type: String
    Default: 'source-bucket'
  CodeCommitSourceKey:
    Type: String
    Default: 'source.zip'
Resources:
  # S3Bucket
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'pipeline-artifacts-bucket-ap-northeast'
  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Let CodeBuild principal have the right for representative access to AWS resources(CodeCommit repository)
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: # AWS Managed Policy to attach to this role
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies: # Custom Policy to attach to this role
        - PolicyName: 'CodeBuildAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Resource: '*'
                Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
  # IAM Role for CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codepipeline.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies: # Custom Policy to attach to this role
        - PolicyName: 'SamplePipelinePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
                Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
              - Resource: '*'
                Effect: 'Allow'
                Action:
                  - 'codecommit:*'
                  - 'codebuild:*'
                  - 's3:*'
    DependsOn:
      - ArtifactBucket
  DeployTargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'deployed-artifact-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        S3: # must refer to the key, so the bucket cannot be created simultaneously
          Bucket: !Ref CodeCommitSourceBucket
          Key: !Ref CodeCommitSourceKey
      RepositoryName: 'CodeRepository'
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: 'NO_ARTIFACTS'
      Environment: # Build runtime environment
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:2.0'
        Type: 'LINUX_CONTAINER'
      LogsConfig:
        CloudWatchLogs:
          GroupName: 'sampleLogsGroup'
          Status: 'ENABLED'
          StreamName: 'sample'
      Name: 'BuildProject'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        BuildSpec: 'client/buildspec.yaml'
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        Location: !GetAtt CodeCommit.CloneUrlHttp
        Type: 'CODECOMMIT'
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: 'S3'
        Location: !Ref ArtifactBucket
      Name: 'samplePipeline'
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'SourceAction'
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Version: 1
                Provider: 'CodeCommit'
              Configuration:
                RepositoryName: !GetAtt CodeCommit.Name
                PollForSourceChanges: false
                BranchName: 'master'
              RunOrder: 1
              OutputArtifacts:
                - Name: 'sourceArtifact'
        - Name: 'Build'
          Actions:
            - Name: 'BuildAction'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Version: 1
                Provider: 'CodeBuild'
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 1
              InputArtifacts:
                - Name: 'sourceArtifact'
              OutputArtifacts:
                - Name: 'builtArtifact'
        - Name: 'Deploy'
          Actions:
            - InputArtifacts:
                - Name: 'builtArtifact'
              Name: 'DeployAction'
              ActionTypeId:
                Category: 'Deploy'
                Owner: 'AWS'
                Version: 1
                Provider: 'S3'
              RunOrder: 1
              Configuration:
                BucketName: !Ref DeployTargetBucket
                Extract: true
    DependsOn:
      - DeployTargetBucket
      - ArtifactBucket
