AWSTemplateFormatVersion: "2010-09-09"
Outputs:
  OutputVPC:
    Description: "VPC output"
    Value: !Ref MyVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
      Tags:
        -
          Key: "VPC-Tag"
          Value: "value"
  # MyIGW:
  #   Type: AWS::EC2::InternetGateway
  #   Properties:
  #     Tags:
  #       -
  #         Key: "IGW-Tag"
  #         Value: "value"
  # AttachGateway:
  #   Type: AWS::EC2::VPCGatewayAttachment
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     InternetGatewayId: !Ref MyIGW
  # # MySG:
  # #   Type: AWS::EC2::SecurityGroup
  # #   Properties: 
  # #     GroupDescription: "sample"
  # #     GroupName: "my-security-group"
  # #     VpcId: !Ref MyVPC
  # # MyInstance:
  # #   Type: AWS::EC2::Instance
  # #   Properties:
  # #     ImageId: "ami-068a6cefc24c301d2"
  # #     SecurityGroupIds:
  # #       - !Ref MySG
  # #     SubnetId: !Ref MySubnet
  # MySubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     CidrBlock: "10.0.0.0/20"
  #     AvailabilityZone: ap-northeast-1a
  #     Tags:
  #       -
  #         Key: "Subnet-Tag"
  #         Value: "value"
  # MyRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     Tags:
  #       -
  #         Key: "RT-Tag"
  #         Value: "value"
  # SubnetAttach:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref MyRouteTable
  #     SubnetId: !Ref MySubnet
  # MyRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref MyRouteTable
  #     DestinationCidrBlock: "0.0.0.0/0"
  #     GatewayId: !Ref MyIGW
  # # MyCluster:
  # #   Type: AWS::ECS::Cluster
  # #   Properties:
  # #     ClusterName: "sample-cluster"
  # #     Tags:
  # #       -
  # #         Key: "Cluster-Tag"
  # #         Value: "value"
  # # MyTaskDefinition:
  # #   Type: AWS::ECS::TaskDefinition
  # #   Properties:
  # #     ContainerDefinitions:
  # #       - 
  # #         Name: "Nginx"
  # #         Image: "915217444612.dkr.ecr.ap-northeast-1.amazonaws.com/sample-nginx:latest"
  # #         Cpu: 10
  # #         Memory: 512
  # #         Essential: true
  # #     Family: "sample-nginx"
  # #     NetworkMode: "awsvpc"
  # #     Tags: 
  # #       -
  # #         Key: "TD-Tag"
  # #         Value: "value"
  # # MyService:
  # #   Type: AWS::ECS::Service
  # #   Properties:
  # #     DesiredCount: 1
  # #     Cluster: !Ref MyCluster
  # #     LaunchType: EC2
  # #     ServiceName: "sampleNginx"
  # #     TaskDefinition: !Ref MyTaskDefinition
  # #     NetworkConfiguration: 
  # #       AwsvpcConfiguration:
  # #         Subnets:
  # #           - !Ref MySubnet